techrealm/urls.py
from django.contrib import admin
from django.urls import path
from techrealm import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', views.blogs, name="blogs"),
    path('', views.inicio, name="inicio"),
    path('login/', views.login_request, name = "login"),
    path('register/', views.register, name = 'register'),
    path('logout/', views.logout_view, name='logout'),
    path('crearBlogs/', views.crear_blog, name='crear_blog'),
    path('blogs/<int:pk>/', views.blogsDetailView.as_view(), name = 'detalle_blog'),
]

techrealm/models.py
from django.db import models

class Cursos(models.Model):
    nombre = models.CharField(max_length=100)
    
    niveles = {
        "1": "Básico",
        "2": "Intermedio",
        "3": "Avanzado"
    }
    nivel = models.CharField(
        max_length = 1,
        choices = niveles,
        default = "1"
    )

    fecha = models.DateField()

class Blogs(models.Model):

    titulo = models.CharField(max_length=100)
    
    subtitulo = models.CharField(max_length=60)
    
    temas = {
        "1":"GTM",
        "2":"GA4",
        "3":"BQ"
    }
    tema = models.CharField(
        max_length = 1,
        choices = temas,
        default = "1"
    )

    cuerpo = models.TextField(null=True, blank= True)

    autor = models.CharField(max_length=100)

    fecha = models.DateTimeField(auto_now_add=True)

    imagen = models.ImageField(null=True, blank=True, upload_to="imagenes/")


class Libros(models.Model):
    nombre = models.CharField(max_length=100)

    temas = {
        "1":"GTM",
        "2":"GA4",
        "3":"BQ"
    }
    tema = models.CharField(
        max_length= 1,
        choices = temas,
        default = "1"
    )

    codigo = models.CharField(max_length=30)

techrealm/forms.py
from django import forms
from .models import Blogs
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, User

class CursoFormulario(forms.Form):
    nombreCurso = forms.CharField()
    nivelCurso = forms.CharField()
    fechaCurso = forms.DateField()

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blogs
        fields = ['titulo', 'subtitulo', 'tema', 'cuerpo', 'imagen']
        widgets = {
            'titulo': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'nombreBlog',
                'placeholder': 'Ingrese el nombre de un blog',
                'required': True
            }),
            'subtitulo': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'subtituloBlog',
                'placeholder': 'Ingrese el subtítulo',
                'required': True
            }),
            'tema': forms.Select(attrs={
                'class': 'form-select',
                'id': 'temaBlog',
                'aria-label': 'Default select example'
            }),
            'cuerpo': forms.Textarea(attrs={
                'class': 'form-control',
                'id': 'cuerpoBlog',
                'placeholder': 'Ingrese el contenido del blog',
                'rows': 5
            }),
            'imagen': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'id': 'imagenBlog'
            }),
        }

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Ingresa tu nombre de usuario',
            'id': 'id_username'
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Ingresa tu contraseña',
            'id': 'id_password'
        })
    )

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(
        required=True,
        label="Usuario",
        widget=forms.TextInput(attrs={
            'class': 'form-control', 
            'placeholder': 'Ingresa tu nombre de usuario',
            'id': 'id_username'
        })
    )
    email = forms.EmailField(
        required=True,
        label="Correo Electrónico",
        widget=forms.EmailInput(attrs={
            'class': 'form-control', 
            'placeholder': 'Ingresa tu correo electrónico',
            'id': 'id_email'
        })
    )
    password1 = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control', 
            'placeholder': 'Ingresa tu contraseña',
            'id': 'id_password1'
        })
    )
    password2 = forms.CharField(
        label="Repetir Contraseña",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control', 
            'placeholder': 'Repite tu contraseña',
            'id': 'id_password2'
        })
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k: "" for k in fields}
        
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.is_staff = True  # Establecer is_staff a True
        if commit:
            user.save()
        return user

techrealm/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from techrealm.models import *
from techrealm.forms import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView

def blogs(request):
    flagBusqueda = False
    if request.method == 'POST':

        tituloBlogs = request.POST.get('titulo')
        blogs = Blogs.objects.filter(titulo__icontains = tituloBlogs)
        flagBusqueda = True
    else:
        blogs = Blogs.objects.all()
    contexto = {"flag": flagBusqueda,"blogs": blogs}
    return render(request, 'blogs.html', contexto)

class blogsDetailView(DetailView):
    model = Blogs
    template_name = "blog_detalle.html"

def cursos(request):
    if request.method == "POST":
        miFormulario = CursoFormulario(request.POST)
        if miFormulario.is_valid:
            curso = Cursos(nombre = request.POST.get('nombreCurso'), nivel = request.POST.get('nivelCurso'), fecha = request.POST.get('fechaCurso'))
            curso.save()
    return render(request, 'cursos.html')
    
def inicio(request):
    flagBusqueda = False
    if request.method == 'POST':
        nombreCurso = request.POST.get('nombreCurso')
        cursos = Cursos.objects.filter(nombre__icontains = nombreCurso)
        flagBusqueda = True
    else:
        cursos = Cursos.objects.all()
    contexto = {"flag": flagBusqueda,"cursos": cursos}
    return render(request, 'inicio.html', contexto)

def libros(request):
    if request.method == 'POST':
        libro = Libros(nombre = request.POST.get('nombreLibro'), tema = request.POST.get('temaLibro'), codigo = request.POST.get('codigoLibro'))
        libro.save()
    return render(request, 'libros.html')

def login_request(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get('username')
            contra = form.cleaned_data.get('password')

            user = authenticate(username=usuario, password=contra)

            if user is not None:
                login(request, user)
                return redirect('inicio')
            else:
                messages.error(request, "Datos incorrectos")
        else:
            messages.error(request, "Error en el formulario, verifica los datos ingresados")
    else:
        form = CustomAuthenticationForm()
    
    return render(request, 'login.html', {'form': form})

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)  # Usa tu formulario personalizado aquí
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            return redirect('login')
        else:
            print(form.errors)
    else:
        form = UserRegisterForm()  # Usa tu formulario personalizado aquí
    
    return render(request, 'registro.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('inicio')

@login_required
def crear_blog(request):
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.autor = request.user.username
            blog.save()
            return redirect('inicio') 
    else:
        form = BlogForm()
    return render(request, 'crear_blog.html', {'form': form})

templates/blog_detalle.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<div class="container mt-5">
    <div class="card">
        <div class="card-header text-center">
            <h1 class="card-title">{{ object.titulo }}</h1>
            <h2 class="card-subtitle text-muted">{{ object.subtitulo }}</h2>
        </div>
        <div class="card-body">
            <p class="card-text"><strong>Tema:</strong> {{ object.get_tema_display }}</p>
            <p class="card-text">{{ object.cuerpo }}</p>
        </div>
        <div class="card-footer text-muted">
            <p><strong>Autor:</strong> {{ object.autor }}</p>
            <p><strong>Fecha:</strong> {{ object.fecha|date:"d M Y, H:i" }}</p>
        </div>
        {% if object.imagen %}
            <img src="{{ object.imagen.url }}" class="card-img-bottom img-fluid rounded mx-auto d-block mt-3 mb-3" alt="Imagen relacionada con el blog">
        {% endif %}
    </div>
    <div class="mt-4 text-center my-3">
        <a href="{% url 'blogs' %}" class="btn btn-primary">Volver a la lista de blogs</a>
    </div>
</div>
{% endblock %}

templates/blogs.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<div class="col-4 mb-4 mt-3 py-3 px-3 mx-auto border border-dark-subtle border-1 rounded-4">
  <h2 class="text-center pb-2">Busca un Blog</h2>
    <form method="POST" action="{% url 'blogs' %}"> {% csrf_token %}
      <div class="mb-3">
          <label for="tituloBlog" class="form-label">Nombre del blog</label>
          <input type="text" class="form-control" id="tituloBlog" name="titulo" placeholder="Ingrese el nombre de un blog">
        </div>
      <div class="col-12 align-self-center mx-auto py-2">
          <button type="submit" class="btn btn-primary col-4 offset-4">Buscar</button>
      </div>
    </form>
  </div>
{% if flag == False %}
<div class="col-8 offset-2 mb-4 py-3 px-3 mx-auto">
<h3 class="text-center pb-3">Lista de Blogs</h3>

{% for blog in blogs %}
<div class="card border-dark mb-3 col-12">
  <div class="card-header">{% if blog.tema == "1" %}
    GTM
{% elif blog.tema == "2" %}
    GA4
{% elif blog.tema == "3" %}
    BQ
{% else %}
    Desconocido
{% endif %}</div>
  <div class="card-body">
    <a href="{% url 'detalle_blog' blog.pk %}"><h5 class="card-title text-center" >{{ blog.titulo }}</h5></a>
    <p class="card-text text-justify">{{ blog.cuerpo }}</p>
  </div>
  <div class="card-footer bg-transparent border-dark" >Autor: {{ blog.autor }} - Fecha: {{blog.fecha}}</div>
</div>
{% endfor %}
</div>
{% else %}
<div class="col-8 offset-2 mb-4 py-3 px-3 mx-auto">
  <h3 class="text-center pb-3">Lista de Blogs</h3>
  
  {% for blog in blogs %}
  <div class="card border-dark mb-3 col-12">
    <div class="card-header">{% if blog.tema == "1" %}
      GTM
  {% elif blog.tema == "2" %}
      GA4
  {% elif blog.tema == "3" %}
      BQ
  {% else %}
      Desconocido
  {% endif %}</div>
    <div class="card-body">
      <h5 class="card-title" >{{ blog.titulo }}</h5>
      <p class="card-text text-justify">{{ blog.cuerpo }}</p>
    </div>
    <a class="card-footer bg-transparent border-dark" href="{% url 'detalle_blog' blog.pk %}">Autor: {{ blog.autor }} - Fecha: {{blog.fecha}}</a>
  </div>
  {% endfor %}
  </div>
  {% endif %}
{% endblock %}

templates/crear_blog.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<div class="col-4 my-4 py-3 px-3 mx-auto border border-dark-subtle border-1 rounded-4">
  <h2 class="text-center pb-2">Registra un Blog</h2>
  <form method="POST" action="{% url 'crear_blog' %}" enctype="multipart/form-data"> 
    {% csrf_token %}
    
    <!-- Nombre del blog -->
    <div class="mb-3">
      <label for="{{ form.titulo.id_for_label }}" class="form-label">Nombre del blog</label>
      {{ form.titulo }}
    </div>
    
    <!-- Subtítulo del blog -->
    <div class="mb-3">
      <label for="{{ form.subtitulo.id_for_label }}" class="form-label">Subtítulo</label>
      {{ form.subtitulo }}
    </div>

    <!-- Tema del blog -->
    <div class="mb-3">
      <label class="pb-3" for="{{ form.tema.id_for_label }}">Tema</label>
      {{ form.tema }}
    </div>

    <!-- Cuerpo del blog -->
    <div class="mb-3">
      <label for="{{ form.cuerpo.id_for_label }}" class="form-label">Cuerpo del blog</label>
      {{ form.cuerpo }}
    </div>

    <!-- Imagen del blog -->
    <div class="mb-3">
      <label for="{{ form.imagen.id_for_label }}" class="form-label">Imagen</label>
      {{ form.imagen }}
    </div>

    <!-- Botón de Envío -->
    <div class="col-12 align-self-center mx-auto py-2">
      <button type="submit" class="btn btn-primary col-4 offset-4">Enviar</button>
    </div>
  </form>
</div>

{% endblock %}

templates/inicio.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<div id="carouselExample" class="my-5 carousel slide col-11 mx-auto w-50 h-70" data-bs-touch="false">
  <div class="carousel-inner col-12">
    <div class="carousel-item active col-12" data-bs-interval="2000">
      <img src="https://res.cloudinary.com/highereducation/image/upload/v1533591754/TheBestColleges.org/study-notebooks.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item col-12" data-bs-interval="2000">
      <img src="https://www.sacap.edu.za/wp-content/uploads/2023/10/unique-study-tips-sacap.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item col-12" data-bs-interval="2000">
      <img src="https://www.heysigmund.com/wp-content/uploads/Studying-9-Scientifically-Proven-Ways-to-Supercharge-Your-Learning.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
  </button>
</div>
{% endblock %}

templates/libros.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<div class="col-4 mb-4 py-3 px-3 mx-auto border border-dark-subtle border-1 rounded-4">
  <h2 class="text-center pb-2">Registra un Libro</h2>
    <form method="POST" action="{% url 'libros' %}"> {% csrf_token %}
      <div class="mb-3">
          <label for="nombreLibro" class="form-label">Nombre del libro</label>
          <input type="text" class="form-control" id="nombreLibro" name="nombreLibro" placeholder="Ingrese el nombre de un libro">
        </div>
      <div class="mb-3">
        <label class="pb-3" for="temaLibro">Tema</label>
        <select class="form-select" id="temaLibro" name="temaLibro" aria-label="Default select example">
          <option value="1" selected >GTM</option>
          <option value="2">GA4</option>
          <option value="3">BQ</option>
        </select>
      </div>
      <div class="mb-3">
        <label for="codigoLibro" class="form-label">Código</label>
        <input type="number" class="form-control" id="codigoLibro" name="codigoLibro" placeholder="Ingrese el código del libro">
      </div>
      <div class="col-12 align-self-center mx-auto py-2">
          <button type="submit" class="btn btn-primary col-4 offset-4">Enviar</button>
      </div>
    </form>
  </div>
{% endblock %}

templates/login.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

<div class="col-4 mb-4 py-3 px-3 mx-auto border border-dark-subtle border-1 rounded-4">
    <h2 class="text-center pb-2">Login</h2>
    
    <!-- Mostrar mensajes de éxito o error -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'login' %}">
        {% csrf_token %}

        <!-- Campo de Usuario -->
        <div class="mb-3">
            <label for="{{ form.username.id_for_label }}" class="form-label">Usuario</label>
            {{ form.username }}
            {% if form.username.errors %}
                <div class="text-danger">
                    {{ form.username.errors }}
                </div>
            {% endif %}
        </div>

        <!-- Campo de Contraseña -->
        <div class="mb-3">
            <label for="{{ form.password.id_for_label }}" class="form-label">Contraseña</label>
            {{ form.password }}
            {% if form.password.errors %}
                <div class="text-danger">
                    {{ form.password.errors }}
                </div>
            {% endif %}
        </div>

        <!-- Botón de Envío -->
        <div class="col-12 align-self-center mx-auto py-2">
            <button type="submit" class="btn btn-primary col-4 offset-4">Ingresar</button>
        </div>
    </form>
</div>
{% endblock %}

templates/logout.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<div class="col-4 mb-4 mt-3 py-3 px-3 mx-auto border border-dark-subtle border-1 rounded-4">
    <h2 class="text-center pb-2">Registrarse</h2>
    <form method="POST" action="{% url 'register' %}"> 
        {% csrf_token %}
        
        <!-- Campo de Usuario -->
        <div class="mb-3">
            <label for="{{ form.username.id_for_label }}" class="form-label">Usuario</label>
            {{ form.username }}
            {% if form.username.errors %}
                <div class="text-danger">
                    {{ form.username.errors }}
                </div>
            {% endif %}
        </div>
        
        <!-- Campo de Correo Electrónico -->
        <div class="mb-3">
            <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
            {{ form.email }}
            {% if form.email.errors %}
                <div class="text-danger">
                    {{ form.email.errors }}
                </div>
            {% endif %}
        </div>
        
        <!-- Campo de Contraseña -->
        <div class="mb-3">
            <label for="{{ form.password1.id_for_label }}" class="form-label">Contraseña</label>
            {{ form.password1 }}
            {% if form.password1.errors %}
                <div class="text-danger">
                    {{ form.password1.errors }}
                </div>
            {% endif %}
        </div>
        
        <!-- Campo de Repetir Contraseña -->
        <div class="mb-3">
            <label for="{{ form.password2.id_for_label }}" class="form-label">Repetir Contraseña</label>
            {{ form.password2 }}
            {% if form.password2.errors %}
                <div class="text-danger">
                    {{ form.password2.errors }}
                </div>
            {% endif %}
        </div>

        <!-- Botón de Envío -->
        <div class="col-12 align-self-center mx-auto py-2">
            <button type="submit" class="btn btn-primary col-4 offset-4">Registrarse</button>
        </div>
    </form>
</div>
{% endblock %}

templates/padre.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Teach Realm</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'inicio' %}">Tech Realm</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
              <ul class="nav nav-pills nav-justified navbar-nav col-6">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'blogs' %}">Blogs</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'crear_blog' %}">Nuevo Blog</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="#">Acerca de mí</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">{% if user.is_authenticated %}
                    {{ user.username }}
                {% else %}
                    Login
                {% endif %}</a>
                  <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sesión</a></li>
                    {% else %}
                    <li><a class="dropdown-item" href="{% url 'login' %}">Iniciar sesión</a></li>
                    <li><a class="dropdown-item" href="{% url 'register' %}">Registrarme</a></li>
                    {% endif %}
                  </ul>
                </li>
              </ul>
            </div>
          </div>
    </nav>
      {% block contenidoQueCambia %}

      {% endblock %}
    <div class="p-4 bg-black bg-gradient text-white text-center">Curso de Python - Flavia Estrada</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/registro.html
{% extends "padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<div class="col-4 mb-4 mt-3 py-3 px-3 mx-auto border border-dark-subtle border-1 rounded-4">
    <h2 class="text-center pb-2">Registrarse</h2>
    <form method="POST" action="{% url 'register' %}"> 
        {% csrf_token %}
        
        <!-- Campo de Usuario -->
        <div class="mb-3">
            <label for="{{ form.username.id_for_label }}" class="form-label">Usuario</label>
            {{ form.username }}
            {% if form.username.errors %}
                <div class="text-danger">
                    {{ form.username.errors }}
                </div>
            {% endif %}
        </div>
        
        <!-- Campo de Correo Electrónico -->
        <div class="mb-3">
            <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
            {{ form.email }}
            {% if form.email.errors %}
                <div class="text-danger">
                    {{ form.email.errors }}
                </div>
            {% endif %}
        </div>
        
        <!-- Campo de Contraseña -->
        <div class="mb-3">
            <label for="{{ form.password1.id_for_label }}" class="form-label">Contraseña</label>
            {{ form.password1 }}
            {% if form.password1.errors %}
                <div class="text-danger">
                    {{ form.password1.errors }}
                </div>
            {% endif %}
        </div>
        
        <!-- Campo de Repetir Contraseña -->
        <div class="mb-3">
            <label for="{{ form.password2.id_for_label }}" class="form-label">Repetir Contraseña</label>
            {{ form.password2 }}
            {% if form.password2.errors %}
                <div class="text-danger">
                    {{ form.password2.errors }}
                </div>
            {% endif %}
        </div>

        <!-- Botón de Envío -->
        <div class="col-12 align-self-center mx-auto py-2">
            <button type="submit" class="btn btn-primary col-4 offset-4">Registrarse</button>
        </div>
    </form>
</div>
{% endblock %}